### ISSUE TITLE
Excluded apps are not permanent

### ISSUE THREAD

**Issue by grhajdu** [krasanen/zen-launcher#1]
Dear Krasanen,

It seems I've encounted a bug that is not present in KISS, only in Zen. I used the Zen button to open the all apps list and excluded "from Zen" a lot that has no business there because they are run from the settings, not indirectly -- icon sets, keyboards and widgets. But then I switched to another launcher and when I returned to Zen, all these apps were in the list again! I repeated the whole process once more but the results were the same. (In KISS the apps I make disappear this way remain so permanently.)

My copy of Zen is the latest version; phone is an old Samsung A 520F running Android 8.0.

All the best!

**Comment by krasanen** [comment]
Fixed when rebasing Kiss changes. Can you @grhajdu try latest Beta release to check that it works. Thanks for the report!
