### ISSUE TITLE
Issue in the Zen launcher - Swiftkey suggestions disabled even after toggle off

### ISSUE THREAD

**Issue by PaduaPlay** [krasanen/zen-launcher#10]
Issue in the Zen launcher - Swiftkey suggestions disabled even after toggle off

The Swiftkey app works well, for me, because over a period of time it has learnt the complex spelling many of my contacts and the suggestions save a lot of typing and editing time.

When searching on the Zen app - even with setting set to off - the suggestions bar in Swiftkey is not displayed.

Please look into this and fix.

Using version dated 2022-09-24.

Thanks for considering.

**Comment by krasanen** [comment]
Thanks for the report, fix is on the way :+1:
