### ISSUE TITLE
Only one contact is displayed when two contacts have the same name

### ISSUE THREAD

**Issue by PaduaPlay** [krasanen/zen-launcher#11]
Issue in the Zen launcher - only one contact is displayed when two contacts have the same name.

When two contacts have the same name but different phone numbers only one contact is displayed - sometimes. And, sometimes, after a couple of restarts of the app it shows both contacts. Not reliably repeatable. 

(Just fyi, in case it helps in the fix process - this works fine with the KISS app - all contacts with the same name are displayed)

Perhaps a settings option to rebuild index will fix this?

Please look into this.

Using version 2022-11-25@dc8ba83d Updated on Nov 25, 2022.

Thanks for considering.

**Comment by krasanen** [comment]
Thanks for the report. This seems to be hard to reproduce, not happening on my personal device or in emulator. KISS and ZEN have similar code used to react on newly added contact, did not find any difference there that could explain this. KISS has added code to react on lost contacts permission, but if permission would be lost, all contacts would stop showing.

Can you catch the logic on how it reproduces?

There is setting to restart only Zen Launcher if this happens, go to Zen Launcher settings / Advanced settings / Restart Zen Launcher, does this bring the issue up if repeated many times (not for me at least).

**Comment by PaduaPlay** [comment]
Thank you for the quick response.

Correct - it does seem not predictably incorrect when showing only one contact - as mentioned in the OP on Git.

On my device, both KISS and Zen have the same permissions and since I use Zen more frequently, it does not seem to be any permissions issue.

Could it be that when Zen finds a contact name repeated it has some logic to 'avoid duplicates' that gets triggered some times?

I do use the Zen app restart option when needed.

As suggested, perhaps, a refresh index option that can be run manually would avoid this? Of course, as the developer, you would know better about this.

Will try it out a few more times to see if a repeatable logic can be identified.

**Comment by PaduaPlay** [comment]
This seems to be happening once after a restart of the device. But, after one run and restart of the app, it seems to work fine.. Not sure if this is adequate enough info to look further into solving this issue. Thanks again.

**Comment by krasanen** [comment]
@PaduaPlay are you on beta testers? Found some differences with KISS to be ruled out. Could you try out above fix that is included on Beta track, version will be 1406 (2022-12-23@8b441c90)

**Comment by PaduaPlay** [comment]
> @PaduaPlay are you on beta testers? Found some differences with KISS to be ruled out. Could you try out above fix that is included on Beta track, version will be 1406 (2022-12-23@8b441c90)

Haven't signed up for beta on this app because I use it regularly and prefer the stability. Will try out the version suggested. Is there a side load option - can I download the apk of the beta from somewhere? Didn't see it on the git releases page.

Thanks again for the follow up on this.

**Comment by krasanen** [comment]
It seems to work ok for what I was able to test, started to roll it out to production. At least it will fix issue with badges on my device, let's see what happens with this issue.

@PaduaPlay could you try to reproduce this contact issue with latest production version and let me know if it helps?
