### ISSUE TITLE
Feature request : Add 'view contact' to the long touch options

### ISSUE THREAD

**Issue by PaduaPlay** [krasanen/zen-launcher#13]
Adding 'view contact' to the long touch options would be very useful to view further details of the contact.

Useful when the contact has many numbers, or if there are many contacts with same / similarly spelt names etc.

Thanks for considering..

**Comment by krasanen** [comment]
Thanks for the feature request. Clicking contact picture already opens contact details, would it make sense to add it also to long press menu?

**Comment by PaduaPlay** [comment]
Didn't know that clicking on the contact picture brings up the contact details - have *never* used contact photos in any app / device!  

Clicking where the photo would have been, does bring up the contact details on Zen launcher - so a long press option would really not be needed..

Glad to know about this feature.
