### ISSUE TITLE
[Feature Request] Hide Favorite bar initially

### ISSUE THREAD

**Issue by MicroBeast** [krasanen/zen-launcher#16]
Like in Kiss Launcher. Favorites bar show up if we interact with the screen (Gestures).

The current option completely hide Favorite bar and I found no way to access it then.

It's niche feature I guess. I just like clear Home Screen presented on Kiss Launcher when Favorite bar (or everything) hidden.

**Comment by krasanen** [comment]
Seems like a good improvement from KISS. Could you check out if this is what you are looking for, apk shared in the channel:

https://t.me/zenlauncher

**Comment by MicroBeast** [comment]
Tested. Yes, it's that one. Seem work perfectly.

This can be closed then. Thank you
