### ISSUE TITLE
Freezing issues Zen Launcher

### ISSUE THREAD

**Issue by Mayo70** [krasanen/zen-launcher#2]
I find Zen Launcher to be a really great Launcher option due the simplicity of the search function for apps,
contacts and shortcuts and the fact I can leave the screen really minimal.
The one issue I have is that while scrolling through previous history it seems to freeze or jam and start sliding back to the search bar instead of moving fluidly. 
Also I sometimes have to press an app icon a few times before it opens.
Anyone else have this issue? Otherwise I think it's a great all round use of the Kiss Launcher platform.
My phone is a Samsung Galaxy S10+

**Comment by krasanen** [comment]
Has anyone seen these issues with latest releases?

**Comment by krasanen** [comment]
Happened on my Galaxy S7 but very rarely, I'm quite sure this comes from badge provider on Samsung devices bombarding badge updates. As a first remedy I think off adding settings option to turn badge updates off on Samsung devices

**Comment by krasanen** [comment]
Fix rolling out into beta, @Mayo70, would love to know if it works now.

**Comment by Mayo70** [comment]
Yes. It's working perfectly now. Thank you very much for your help

**Comment by krasanen** [comment]
Thanks!
