### ISSUE TITLE
Apps (other than preinstalled factory) not showing up 

### ISSUE THREAD

**Issue by djworx123** [krasanen/zen-launcher#3]
I have the latest zen launcher installed.

Device is Samsung M01 on android 11.

I am also running KISS launcher in parallel and it works perfectly fine. But in zen launcher, other than the preinstalled samsung apps, none of the apps turn up. I tried searching for them, looked in the list etc, but no luck!

Would appreciate a fix since this looks like the launcher  that I would like to stick with.

Thanks!

**Comment by beane** [comment]
The same thing happened to me! I'm running Android 11 on a Pixel 4a. Preinstalled Google apps and settings show up, but no apps that I installed.

Love Zen Launcher and I would really appreciate a fix!

**Comment by krasanen** [comment]
Resolved with this commit:
https://github.com/krasanen/zen-launcher/commit/6ea811320503782aac9b93a80b7ccdc459379a8b
