### ISSUE TITLE
Unnecessary frame around icons

### ISSUE THREAD

**Issue by grhajdu** [krasanen/zen-launcher#4]
Not with all icon packs but quite a number, this unneeded frame appears. Example is Kaorin in Zen and two other launchers
![Screenshot_20211023-093243_Niagara Launcher](https://user-images.githubusercontent.com/64653481/138547768-fbf19cd6-0fca-48af-9d6b-789def3fb493.jpg)
![Screenshot_20211023-093310_Smart Launcher Pro](https://user-images.githubusercontent.com/64653481/138547770-f0075c60-e615-40b2-acef-59b85a7b69a4.jpg)
![Screenshot_20211023-093155_Zen Launcher](https://user-images.githubusercontent.com/64653481/138547773-7f18a5c6-14e6-4a4c-88d0-0bc3369537b4.jpg)
 
(Samsung A520-F, Android 8.0)

**Comment by krasanen** [comment]
Any free icon packs that reproduce this issue?

**Comment by grhajdu** [comment]
OxyPie is a free one that behaves like this: 
![Screenshot_20211126-221910_Zen Launcher](https://user-images.githubusercontent.com/64653481/143656632-6bda2cdf-519c-4a3d-be13-824c0c27d710.jpg)
![Screenshot_20211126-222124_Niagara Launcher](https://user-images.githubusercontent.com/64653481/143656637-5dc07df5-e5bc-474c-bb9c-15533ca872e4.jpg)

**Comment by krasanen** [comment]
Here is a setting that seems to fix the issue, let me know if this works for you also:
3 dot menu / Zen Launcher settings / User interface / Force icon background

And after enabling it, restart Zen to reload icons with:
3 dot menu / Zen Launcher settings / Advanced settings / Restart Zen Launcher

**Comment by grhajdu** [comment]
Thank you, this solved the problem.
