### ISSUE TITLE
slow drawer and list view

### ISSUE THREAD

**Issue by xi7** [krasanen/zen-launcher#6]
https://user-images.githubusercontent.com/67331785/146360722-90b0ef5f-193a-46a8-be5c-86a8bd4995fe.mp4

**Comment by krasanen** [comment]
Does this happen only for first opening or always. App icons should be cached for faster usage after first open.

**Comment by xi7** [comment]
**always load with lag.** and not too much apps

another problem when pick favorites, we cant search and also disappear listview gridview.

**Comment by krasanen** [comment]
Do you have icon cache enabled? 
Zen Launcher settings / use experience / keep icons in memory.

For the search issue, check that this is not enabled:
Zen Launcher settings / Favorites settings / Exclude favorites from app list

**Comment by xi7** [comment]
https://user-images.githubusercontent.com/67331785/146526436-044ae2e9-178d-4f3e-afc6-2f6f773ab64b.mp4

keep icons in memory the grid_view work better but i think still not best solution, and list_view still very slow.

(the search issue solved here tnks)

**Comment by krasanen** [comment]
@xi7 upcoming release "1391 (2022-01-21@7b31feda)" will contain applist handling optimizations. Could you test with it? Thanks.

**Comment by krasanen** [comment]
Closing as not active. Please reopen separate issue off applist problem if it still reproduces.
