### ISSUE TITLE
features 

### ISSUE THREAD

**Issue by xi7** [krasanen/zen-launcher#7]
hide apps and drawer no label onepage like glow launcher 

https://play.google.com/store/apps/details?id=go.fuck.go

**Comment by xi7** [comment]
https://play.google.com/store/apps/details?id=go.fuck.jellyfish

or overlay drawer using keymapper , very interesting!

**Comment by krasanen** [comment]
Interesting ideas! Onepage was kind of nice, but if you have lots of apps, icons get too small. Overlay was also cool. Let's keep these here for open discussion :)

**Comment by xi7** [comment]
https://user-images.githubusercontent.com/67331785/160456985-e5235a0d-60db-471c-b6be-ae0885a1f594.mp4

overlay ... widgets with flip fav apps and search , infinite bar :)
