### ISSUE TITLE
'Error message - "Could not add shortcut. Is Zen your default launcher?"

### ISSUE THREAD

**Issue by PaduaPlay** [krasanen/zen-launcher#9]
Issue in the Zen launcher (not KISS): 'Error message' on startup when Zen is not set as the default launcher.

This is the 'error message' - "Could not add shortcut. Is Zen your default launcher?"

The app works fine but, what shortcut is it trying to add?

Can this be set to 'don't add' and avoid this 'error message'.  It is just a little bit annoying..

Using version dated 2022-09-24.

Thanks for considering.

**Comment by krasanen** [comment]
Thanks for the report, this is now fixed and will be on next release.
